image: quay.io/librelabs/ci:dind17

adfs plugin-test:
  stage: test
  before_script:
    - git clone https://github.com/asdf-vm/asdf.git
    - . asdf/asdf.sh
  script:
    - asdf plugin-add tilt ./
    - asdf list-all tilt
    - asdf plugin-test tilt ./ 'tilt help' || exit 1
