image: quay.io/librelabs/ci:dind17

tilt-plugin-test:
  stage: test
  before_script:
    - apk update && apk add util-linux
    - git clone https://github.com/asdf-vm/asdf.git
    - . asdf/asdf.sh
  script:
    - asdf plugin-add tilt $CI_REPOSITORY_URL
    - asdf plugin update tilt $CI_COMMIT_REF_NAME
    - asdf list-all tilt
    - asdf plugin test tilt $CI_REPOSITORY_URL --asdf-plugin-gitref $CI_COMMIT_REF_NAME 'tilt version' || exit 1
