image: quay.io/librelabs/ci:dind17

tilt-plugin-test:
  stage: test
  before_script:
    - apk update && apk add util-linux
    - git clone https://github.com/asdf-vm/asdf.git
    - . asdf/asdf.sh
  script:
    - asdf plugin-add tilt https://gitlab.com/wt0f/asdf-tilt.git
    - asdf list-all tilt
    - asdf plugin test tilt https://gitlab.com/wt0f/asdf-tilt.git 'tilt version' || exit 1
